### ISSUE TITLE
broken link to python-basic

### ISSUE THREAD

**Issue by sbinet** [histogrammar/histogrammar-docs#19]
it seems the link to the "Basic use in python" tutorial is broken:

```
$> curl http://histogrammar.org/docs/tutorials/python-basic
[...]
  <p>Sorry, but the page you were trying to view does not exist.</p>
```

**Comment by sbinet** [comment]
I guess it's a side-effect of 8d4f0f77893e2a38adcf33501c41b371bf8a6af0

**Comment by jpivarski** [comment]
Yeah, the 0% done tutorials are blank pages. They were there to remind me that they need to be written.

But you know what? Visitors to the website shouldn't see that. I just commented out all tutorials with 0% completion: 1c50dc997961552f4bdd007464fc586e749d3356
