### ISSUE TITLE
Categorize: Function returns a double

### ISSUE THREAD

**Issue by isaacsanders** [histogrammar/histogrammar-docs#20]
The specification states that the function passed to `Categorize`, `quantity`, takes a data point and returns a `double`. I feel like a more appropriate name may be `category`, as well as the correction that it should return a `string`.

[Source](https://github.com/histogrammar/histogrammar-docs/blob/master/specification/1.1/index.md#categorizing-constructor-and-required-members)

**Comment by jpivarski** [comment]
That's a copy-paste error. The function accepted by Categorize takes a function that returns a string. The Scala implementation is explicit about that.

**Comment by jpivarski** [comment]
Fixed.
