### ISSUE TITLE
SparselyBin's "binWidth" is the only camelCased field in the entire specification.

### ISSUE THREAD

**Issue by isaacsanders** [histogrammar/histogrammar-docs#21]
I was implementing `SparselyBin` for Elixir, and I realized that `binWidth` is the only static key in the entire specification that is noticeably camelCased.

Everything else is either a single word, or a colon delimited specifier. That naming scheme is quite strict, too, where ":type" and ":name" are the only two suffices that are present in the specification.

For specification version 2.0, I propose `binWidth` is changed to something that doesn't violate case-scheme agnosticism.

**Comment by jpivarski** [comment]
Good point. There used to be more camel-cased attributes, but if it's down to this one, we can think about a replacement that avoids it altogether.

For this example, what do you think about just "width?" For the Bin aggregator, there'd be an ambiguity between the width of a bin and the width of the domain ("high minus low"). For SparselyBin, the domain is infinite, so there's​ no ambiguity, but could there be confusion anyway?

**Comment by isaacsanders** [comment]
I considered this option as well. I think it may be the best choice if the change is what we go with. All other binning primitives have their own unique definitions of width.

The conflation with the domain is definitely a negative point of the idea. Do you think any of the other maintainers have a strong opinion?

**Comment by jpivarski** [comment]
Let's see if they comment.  :)

I'm pretty sure Alexey also gets these notifications.

**Comment by ASvyatkovskiy** [comment]
Yes I am :)
I do not have a strong opinion
